name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install kivy kivymd
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          pkg-config \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          python3 \
          python3-pip \
          build-essential \
          libsqlite3-dev \
          zlib1g-dev

    - name: Build APK
      run: |
        pip install buildozer
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: SAP-URO-APK
        path: bin/SAP-URO-0.1-debug.apk
